# Generated by Django 5.0.1 on 2024-03-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='confirmpassword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='sdp',
        ),
    ]
